#!/bin/bash
#SBATCH -p htc-el8 # partiion
#SBATCH -J ising # Job name
#SBATCH -a 0-7 #Job array
#SBATCH -N 1 # Number of nodes
#SBATCH -n 2 # Number of cpus in node
#SBATCH --mem 8G
#SBATCH -t 2-00:00:00
#SBATCH -o slurm/%A_%a.log
#SBATCH -e slurm/%A_%a.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=sabrina.savino@embl.de

# Prologue
echo Working at `hostname`:`pwd` \(`date`\)
SECONDS=0
module purge
source /g/erzberger/savino/miniconda3/etc/profile.d/conda.sh # NB!
conda activate

python examples/4_spins/run4.py -i "[${SLURM_ARRAY_TASK_ID}]"

# Epilogue
duration=$SECONDS
days=$((duration / 86400))
hours=$((duration % 86400 / 3600))
minutes=$((duration % 3600 / 60))
seconds=$((duration % 60))
echo "Elapsed time: $days-$hours:$minutes:$seconds"
